name: Create Release from Tag

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: Release Built Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Wait 30s for Builds to Complete
        run: sleep 30s
        shell: bash
      - name: Download Artifacts
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: main
          workflow: build.yml
          workflow_conclusion: success
          if_no_artifact_found: fail
          skip_unpack: true
      - name: Automatic Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          draft: true
          files: |
            *.zip
